version: '3.9'

services:

  vue:
    container_name: saasoft-app
    image: node:18
    tty: true
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - 3000:3000